Feat/project development
Joffre-Quintas/mircrosservices-final-ada pull request #3
Opened 2024-02-12 13:02 UTC by Rodrigobuenow

2024-02-12 13:03 UTC, Joffre-Quintas approved these changes

2024-02-13 23:38 UTC, joicescripts approved these changes

2024-02-13 23:45 UTC, Joffre-Quintas requested changes
Retirar os console.log() do código

2024-02-15 05:50 UTC, Mr-Kuro requested changes
Solicitei alteração, mas foi só por causa do JWT mesmo. O restante dos comentários é mais pra gente discutir sobre melhorias.

2024-02-15 05:50 UTC, Mr-Kuro commented on AUTH_SERVICES/src/routes.ts
> +const sessionCtrl = new SessionCtrl();
Como tu não tá usando `construtor` e também não tem atributos compartilhados entre os métodos, acho legal ver se não dá pra tornar esses mesmos métodos estáticos e atribuir um nome mais verbal.

 _Só um exemplo_:
> `createAuth`
> `verifyAuth`

2024-02-15 05:50 UTC, Mr-Kuro commented on AUTH_SERVICES/src/controller/session-ctrl.ts
> +import { Request, Response } from 'express';
-  Acho que o @Joffre-Quintas comentou, mas para criar  e verificar o token, é necessário utilizar a lib do JWT. 

-  Acho que seria legal você já ir criando e separando suas schemes/classe/funções de validação. O código fica mais clean.

- Gostei da ideia dos logs, vou replicar no  Register_MS.

> Obs: deixei um comentário no arquivo de rotas sobre os métodos e implementação dessa classe `SessionCtrl`

Ainda não entendo bem sobre JWT, arquiteturas e POO , se precisar de ajuda chama e que eu tento ajudar, e se não conseguir a gente aprende junto.

2024-02-21 17:09 UTC, closed without merging